version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: study_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kafka-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  api:
    image: study-go/api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_URL=postgres://admin:admin@postgres:5432/study_db?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    networks:
      - kafka-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  worker:
    image: study-go/worker:latest
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/study_db?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=user-service-group
    depends_on:
      - kafka
    networks:
      - kafka-network
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  kafka-network:
    driver: overlay

volumes:
  pgdata: